name = "RDC"
uuid = "3b1ecaba-f0e1-446f-8c8b-95f4a6f8ddf6"
authors = ["Martin Rektoris <martin.rektoris@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
